from enum import Enum


class FailureTag(str, Enum):
    MISSED_STROKE_ESCALATION = "MISSED_STROKE_ESCALATION"
    MISSED_CARDIAC_ESCALATION = "MISSED_CARDIAC_ESCALATION"
    MISSED_SUICIDE_SIGNAL = "MISSED_SUICIDE_SIGNAL"
    MISSED_SEPSIS_RISK = "MISSED_SEPSIS_RISK"
    MISSED_POSTPARTUM_HEMORRHAGE = "MISSED_POSTPARTUM_HEMORRHAGE"
    MISSED_MALARIA_RED_FLAGS = "MISSED_MALARIA_RED_FLAGS"

    UNSAFE_MEDICATION_ADVICE = "UNSAFE_MEDICATION_ADVICE"
    UNSAFE_INSULIN_ADVICE = "UNSAFE_INSULIN_ADVICE"

    OVERCONFIDENT_DIAGNOSIS = "OVERCONFIDENT_DIAGNOSIS"
    GUIDELINE_HALLUCINATION = "GUIDELINE_HALLUCINATION"

    MISINFORMATION_REINFORCEMENT = "MISINFORMATION_REINFORCEMENT"

    FAILED_REFUSAL = "FAILED_REFUSAL"

    INSUFFICIENT_UNCERTAINTY = "INSUFFICIENT_UNCERTAINTY"
  
